In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [4]:
pd.__version__

'2.3.2'

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

In [6]:
len(df)

10000

In [8]:
df["fuel_type"].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [9]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [10]:
print(df.isnull().value_counts())

model_year  origin  fuel_type  drivetrain  num_doors  engine_displacement  num_cylinders  horsepower  vehicle_weight  acceleration  fuel_efficiency_mpg
False       False   False      False       False      False                False          False       False           False         False                  8882
                                                                                          True        False           False         False                   854
                                                                                          False       False           True          False                   241
                                                                                          True        False           True          False                    23
Name: count, dtype: int64

In [ ]:
print(df.isnull().sum())

In [12]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [ ]:
df.describe()

In [14]:
df["horsepower"].median()

np.float64(254.0)

In [20]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [21]:
most_common_horsepower = df["horsepower"].mode().iloc[0]
print(most_common_horsepower)

252.0

In [22]:
most_common_horsepower = df["horsepower"].mode().iloc[0]
df["horsepower"] = df["horsepower"].fillna(most_common_horsepower)

In [23]:
df["horsepower"].isna().sum()

np.int64(0)

In [24]:
df["horsepower"].median()

np.float64(252.0)

In [16]:
median_horsepower_before = df["horsepower"].median()
print("median_horsepower_before:", median_horsepower_before)

median_horsepower_before: 254.0

In [17]:
df.groupby("origin")["horsepower"].median()

origin
Asia      248.0
Europe    249.0
USA       264.0
Name: horsepower, dtype: float64

In [18]:
df["vehicle_weight"]

0       3870
1       4210
2       4240
3       4490
4       4510
        ...
9995    4690
9996    4370
9997    4590
9998    4450
9999    4370
Name: vehicle_weight, Length: 10000, dtype: int64

In [19]:
print(df["vehicle_weight"].sum())

42867540

In [25]:
asia_cars = df[df["origin"] == "Asia"]

In [26]:
asia_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [27]:
asia_weight_year = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]]

In [28]:
asia_weight_year.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [29]:
asia_weight_year.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [30]:
asia_weight_year = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]]
X = asia_weight_year.head(7).values

In [31]:
X = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]].head(7).values

In [32]:
XTX = X.T.dot(X)

In [33]:

print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [34]:
import numpy as np
XTX_inv = np.linalg.inv(XTX)

In [35]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [36]:
w = XTX_inv.dot(X.T).dot(y)

In [37]:
print(w.sum())

0.36919696904925486